// Generated by CoffeeScript 1.9.0
(function() {
  $(document).ready(function() {
    var bottom, color, data, div, height, left, node, position, right, top, treemap, width;
    data = simple_treemap;
    top = 40;
    bottom = 10;
    left = 10;
    right = 10;
    width = 960 - left - right;
    height = 500 - top - bottom;
    color = d3.scale.category20c();
    treemap = d3.layout.treemap().size([width, height]).sticky(true).value(function(d) {
      return d.size;
    });
    div = d3.select("body").append("div").style("position", "relative").style("width", (width + left + right) + "px").style("height", (height + top + bottom) + "px").style("left", left + "px").style("top", top + "px");
    position = function() {
      return this.style("left", function(d) {
        return d.x + "px";
      }).style("top", function(d) {
        return d.y + "px";
      }).style("width", function(d) {
        return Math.max(0, d.dx - 1) + "px";
      }).style("height", function(d) {
        return Math.max(0, d.dy - 1) + "px";
      });
    };
    return node = div.datum(data).selectAll(".node").data(treemap.nodes).enter().append("div").attr("class", "node").call(position).style("background", function(d) {
      if (d.children) {
        return color(d.name);
      } else {
        return null;
      }
    }).text(function(d) {
      if (d.children) {
        return null;
      } else {
        return d.name;
      }
    });
  });

}).call(this);
