// Generated by CoffeeScript 1.9.0
(function() {
  var browser_name, format_month;

  browser_name = ["Chrome", "Firefox", "Internet Explorer", "Safari", "Android", "Safari App", "Mozilla Compatible Agent", "Opera"];

  format_month = function(date) {
    var new_date;
    return new_date = date.substring(4, 6) + "/" + date.substring(0, 4);
  };

  window.format_data = function(data) {
    var data_month, dict_browser, dict_month, i, j, journals, month, value;
    journals = {};
    journals["browser"] = [];
    journals["period"] = [];
    i = 0;
    while (i < browser_name.length) {
      dict_browser = {};
      data_month = [];
      dict_browser["name"] = browser_name[i];
      dict_browser["data_month"] = data_month;
      journals.browser[journals.browser.length] = dict_browser;
      i++;
    }
    i = 0;
    while (i < data.data.length) {
      j = 0;
      month = format_month(data.labels.dimensions[i]);
      journals.period[journals.period.length] = month;
      while (j < browser_name.length) {
        value = data.data[i][j];
        dict_month = {};
        dict_month["month"] = month;
        dict_month["value"] = parseInt(value);
        journals.browser[j].data_month[journals.browser[j].data_month.length] = dict_month;
        j++;
      }
      i++;
    }
    return journals;
  };

}).call(this);
