simple_bar_chart = {
    "site" : "monsite.com",
    "browser" : [
        {
            "name" : "A",
            "value_boy" : 8833,
            "value_girl" : 37378,
            "best_boy_name" : "Arthur",
            "best_girl_name" : "Alicia",
        },
        {
            "name" : "B",
            "value_boy" : 4957,
            "value_girl" : 3931,
            "best_boy_name" : "Bastien",
            "best_girl_name" : "Betty",
        },
        {
            "name" : "C",
            "value_boy" : 13029,
            "value_girl" : 21557,
            "best_boy_name" : "Cédric",
            "best_girl_name" : "Céline",
        },
        {
            "name" : "D",
            "value_boy" : 35266,
            "value_girl" : 9731,
            "best_boy_name" : "Dimitri",
            "best_girl_name" : "Diana",
        },
        {
            "name" : "E",
            "value_boy" : 12091,
            "value_girl" : 35595,
            "best_boy_name" : "Eddy",
            "best_girl_name" : "Elise",
        },
        {
            "name" : "F",
            "value_boy" : 8585,
            "value_girl" : 2227,
            "best_boy_name" : "Fabrice",
            "best_girl_name" : "Félicia",
        },
        {
            "name" : "G",
            "value_boy" : 27546,
            "value_girl" : 3353,
            "best_boy_name" : "Grégory",
            "best_girl_name" : "Gisèle",
        },
        {
            "name" : "H",
            "value_boy" : 11987,
            "value_girl" : 20876,
            "best_boy_name" : "Harrison",
            "best_girl_name" : "Henriette",
        },
        {
            "name" : "I",
            "value_boy" : 4119,
            "value_girl" : 4678,
            "best_boy_name" : "Icare",
            "best_girl_name" : "Ingrid",
        },
        {
            "name" : "J",
            "value_boy" : 10082,
            "value_girl" : 20905,
            "best_boy_name" : "Jordan",
            "best_girl_name" : "Jacqueline",
        },
        {
            "name" : "K",
            "value_boy" : 19189,
            "value_girl" : 17609,
            "best_boy_name" : "Kévin",
            "best_girl_name" : "Korina",
        },
        {
            "name" : "L",
            "value_boy" : 6221,
            "value_girl" : 18368,
            "best_boy_name" : "Larry",
            "best_girl_name" : "Laura",
        },
        {
            "name" : "M",
            "value_boy" : 5112,
            "value_girl" : 176,
            "best_boy_name" : "Marvin",
            "best_girl_name" : "Maurane",
        },
        {
            "name" : "N",
            "value_boy" : 37100,
            "value_girl" : 3012,
            "best_boy_name" : "Norbert",
            "best_girl_name" : "Nina",
        },
        {
            "name" : "O",
            "value_boy" : 5670,
            "value_girl" : 40965,
            "best_boy_name" : "Olivier",
            "best_girl_name" : "Odette",
        },
        {
            "name" : "P",
            "value_boy" : 1856,
            "value_girl" : 9090,
            "best_boy_name" : "Paul",
            "best_girl_name" : "Pierrette",
        },
        {
            "name" : "Q",
            "value_boy" : 30015,
            "value_girl" : 2241,
            "best_boy_name" : "Quanton",
            "best_girl_name" : "Quintina",
        },
        {
            "name" : "R",
            "value_boy" : 4875,
            "value_girl" : 16019,
            "best_boy_name" : "Roland",
            "best_girl_name" : "Rita",
        },
        {
            "name" : "S",
            "value_boy" : 2747,
            "value_girl" : 18031,
            "best_boy_name" : "Salomon",
            "best_girl_name" : "Samus",
        },
        {
            "name" : "T",
            "value_boy" : 32785,
            "value_girl" : 11370,
            "best_boy_name" : "Tony",
            "best_girl_name" : "Tatiana",
        },
        {
            "name" : "U",
            "value_boy" : 15047,
            "value_girl" : 2524,
            "best_boy_name" : "Uriel",
            "best_girl_name" : "Ursula",
        },
        {
            "name" : "V",
            "value_boy" : 5729,
            "value_girl" : 3844,
            "best_boy_name" : "Vivien",
            "best_girl_name" : "Victoria",
        },
        {
            "name" : "W",
            "value_boy" : 19829,
            "value_girl" : 12542,
            "best_boy_name" : "Wilfired",
            "best_girl_name" : "Wendy",
        },
        {
            "name" : "X",
            "value_boy" : 3875,
            "value_girl" : 2380,
            "best_boy_name" : "Xavier",
            "best_girl_name" : "Xena",
        },
        {
            "name" : "Y",
            "value_boy" : 22687,
            "value_girl" : 17055,
            "best_boy_name" : "Yannick",
            "best_girl_name" : "Yolande",
        },
        {
            "name" : "Z",
            "value_boy" : 16076,
            "value_girl" : 9332,
            "best_boy_name" : "Zénon",
            "best_girl_name" : "Zoé",
        }
    ]
}


