// Generated by CoffeeScript 1.9.0
(function() {
  $(document).ready(function() {
    var data, get_data_boy, get_data_girl, get_data_letter, get_data_value;
    data = simple_bar_chart.browser;
    get_data_letter = function(letter) {
      return letter;
    };
    get_data_value = function(letter) {
      var data_value, i;
      i = 0;
      while (i < data.length) {
        if (data[i].name === letter) {
          data_value = data[i].value_boy + data[i].value_girl;
          break;
        } else {
          i++;
        }
      }
      return data_value;
    };
    get_data_boy = function(letter) {
      var data_boy, i;
      i = 0;
      while (i < data.length) {
        if (data[i].name === letter) {
          data_boy = data[i].best_boy_name;
          break;
        } else {
          i++;
        }
      }
      return data_boy;
    };
    get_data_girl = function(letter) {
      var data_girl, i;
      i = 0;
      while (i < data.length) {
        if (data[i].name === letter) {
          data_girl = data[i].best_girl_name;
          break;
        } else {
          i++;
        }
      }
      return data_girl;
    };
    return $(".bar").hover(function() {
      var get_id_letter;
      get_id_letter = $(this).attr("id");
      $(this).css("opacity", 0);
      $("#main_zone").css("opacity", 1);
      $(".info_letter").text(get_data_letter(get_id_letter));
      $(".info_value").text(get_data_value(get_id_letter));
      $(".info_boy").text(get_data_boy(get_id_letter));
      return $(".info_girl").text(get_data_girl(get_id_letter));
    }, function() {
      $("#main_zone").css("opacity", 0);
      return $(this).css("opacity", 1);
    });
  });

}).call(this);
