// Generated by CoffeeScript 1.9.0
(function() {
  window.colors = [
    {
      stage: 1,
      stage_color: ["green", "blue", "red", "orange", "yellow", "purple", "pink", "brown"]
    }, {
      stage: 2,
      stage_color: ["green", "blue", "red", "orange", "yellow", "purple", "pink", "brown"]
    }, {
      stage: 3,
      stage_color: ["green", "blue", "red", "orange", "yellow", "purple", "pink", "brown"]
    }, {
      stage: 4,
      stage_color: ["green", "blue", "red", "orange", "yellow", "purple", "pink", "brown"]
    }
  ];

}).call(this);
