// Generated by CoffeeScript 1.9.0
(function() {
  window.get_data = function(query) {
    var url;
    url = "http://127.0.0.1:5000/get_engine_data";
    return $.ajax({
      'url': url,
      'method': 'POST',
      'data': query
    }).done(function(data) {
      return window.result = data;
    });
  };

}).call(this);
