// Generated by CoffeeScript 1.9.0
(function() {
  $(document).ready(function() {
    var query, url;
    query = window.queries;
    url = "http://127.0.0.1:5000/get_engine_data";
    $.ajax({
      'url': url,
      'method': 'POST',
      'data': {
        'query': JSON.stringify(query.query_sessions_per_month_browser)
      }
    }).done(function(data) {
      console.log(JSON.stringify(data, void 0, 4));
      return $("#jason").text(JSON.stringify(data, void 0, 4));
    });
  });

}).call(this);
