// Generated by CoffeeScript 1.9.0
(function() {
  var url;

  url = "http://127.0.0.1:5000/get_engine_data";

  $.ajax({
    'url': url,
    'method': 'POST',
    'data': {
      'query': JSON.stringify(query)
    }
  }).done(function(data) {
    return console.log(JSON.stringify(data));
  });

}).call(this);
